# SITE CONFIGURATION
baseurl: ""
url: "https://paladingroup.github.io"
title: Paladin Group - Developer Blog # site's title
description: "Technology.  Innovation.  Value." # used by search engines

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Developer Blog # blog's title
  avatar: assets/img/paladin-developer-logo.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
   <h2 class="site-title">Paladin Developer Blog</h2>
   <p>Where others see problems, we see solutions!</p>
  header_text_feature_image: assets/img/1px-transparent.png
  footer_text: >
   <!-- Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a> -->
  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: dev@paladingroup.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "paladingroup"
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/company/paladingrouphq/ # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: PaladinGroup # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus:
    tumblr:
    pinterest:
    pocket:
    reddit:
    linkedin: true
    wordpress:
    email: true

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: paladingroup-developer
  katex: false # Enable if using math markup

  special_page:
    search:
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: false

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

  # Post navigation
  post_navigation: true


# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: false
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*", "_legacy/*"]
